# Generated by Django 4.2.1 on 2024-05-29 00:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Register",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
                ("email", models.EmailField(max_length=30)),
                ("phone", models.IntegerField()),
                ("pw", models.CharField(max_length=30)),
                ("addrs", models.TextField(max_length=200)),
            ],
        ),
    ]
